import localFont from "next/font/local";
import TanstackQueryProvider from "@/components/partials/provider/TanstackQueryProvider";
import "./globals.css";
//Components
import Layout from "@/components/layout/Layout";
// import Toaster from "react-hot-toast";
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';



const yekan = localFont({
    src : [
        {
            path: "../../public/fonts/YekanBakh-Regular.woff2",
            weight: "400",
            style: "normal",
        },
        {
            path: "../../public/fonts/YekanBakh-Light.woff2",
            weight: "100",
            style: "normal",
        },
    ]
})

export const metadata = {
  title: "Torino",
  description: "Generated by create next app",
    icons: {
        icon: [
            {
                url: "/icon.png",
                href: "/icon.png",
            },
        ],
    },
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={yekan.className} suppressHydrationWarning={true}>
      <TanstackQueryProvider>
          <Layout>
              {children}
          </Layout>
          <ToastContainer/>
      </TanstackQueryProvider>
      </body>
    </html>
  );
}