import localFont from "next/font/local";
import "./globals.css";
//Components
import Layout from "@/components/layout/Layout";

const yekan = localFont({
    src : [
        {
            path: "../../public/fonts/YekanBakh-Regular.woff2",
            weight: "400",
            style: "normal",
        },
        {
            path: "../../public/fonts/YekanBakh-Light.woff2",
            weight: "100",
            style: "normal",
        }
    ]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={yekan.className}>
         <Layout>
             {children}
         </Layout>
      </body>
    </html>
  );
}
