import SidePage from "@/components/templates/sidePage";

export const metadata = {
    title: "Profile",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="fa" dir="rtl">
        <body suppressHydrationWarning={true}>
        <SidePage>
            {children}
        </SidePage>
        </body>
        </html>
    );
}
